name: s_7_v3
pixel_shift: True
motion_blur: False
add_noise: False
noise_type: none # random # none # constant
sparse_sampling: True
n_gpu: 1
use_gpu: 0

test_data_loader:
  type: TestDataLoader
  args:
    dataset_path: /home/server-3090/REVERSE_ISP/data-s7/s7_test_rgb
    batch_size: 1
    shuffle: False
    num_workers: 1
    debug: False



model:
  type: RISP
  args:
    nFeat: 64

loss:
  loss: loss

metrics: [
    PSNR
]

optimizer:
  type: Adam
  args:
    lr: 0.0001
    betas: [
        0.9,
        0.999
    ]
    weight_decay: 0.0
    amsgrad: False

lr_scheduler:
  type: LambdaLR
  args:
    lr_epoch_reduce: 200


trainer:
  epochs: 500
  save_dir: saved/checkpoints
  save_period_epoch: 5
  validation_epoch: 10
  load_optimizer: False
  save_valid_render_period: 20
  verbosity: 2
  monitor: max CPSNR
  tensorboardX: True
  tensorboard_disp_freq: 1
  log_dir: saved/runs
  render_dir: saved/render
  log_save_dir: saved/test_log_files
  submission_folder: submission

others:
  loss_lambda: 1
  pixel_lambda: 1


